package com.nocturne.session

import kotlinx.coroutines.flow.StateFlow

/**
 * The single interface the whole UI consumes (PLAN §4.3). M1 ships
 * [SimulatedController]; M2 swaps in [EkosRemoteController] over the wire
 * protocol behind the same contract.
 */
interface SessionController {
    val state: StateFlow<SimState>

    fun openSheet(sheet: SheetType)
    fun openDevice(key: String)
    fun closeSheet()
    fun selectTab()
    fun openSubPreview()
    fun closeSubPreview()
    fun requestDeferFlip()
    fun requestFlipNow()
    fun confirmFlipAction()
    fun cancelFlipConfirm()

    fun addToSequence(targetId: String)
    fun removeJob(jobId: String)
    fun openJob(jobId: String)
    fun closeJob()
    fun toggleJobRun(jobId: String)
    fun endSession()
    fun resumeSession()
    fun startNextJob()
    fun finishNight()
    fun toggleBlock(jobId: String, blockId: String)
    fun addBlock(jobId: String)
    fun removeBlock(jobId: String, blockId: String)
    fun moveBlock(jobId: String, blockId: String, toIndex: Int)
    fun cycleBlockFilter(jobId: String, blockId: String)
    fun setBlockExposure(jobId: String, blockId: String, sec: Int)
    fun setBlockSubCount(jobId: String, blockId: String, count: Int)
    fun setBlockGain(jobId: String, blockId: String, gain: Int)
    fun setBlockOffset(jobId: String, blockId: String, offset: Int)
    fun setBlockBinning(jobId: String, blockId: String, bin: Int)
    fun setBlockDither(jobId: String, blockId: String, n: Int)
    fun toggleBlockForceAf(jobId: String, blockId: String)
    fun setAutofocusRefocusMin(min: Int)
    fun setAutofocusTempDelta(deltaC: Double)
    fun toggleAutofocusOnFilterChange()
    fun toggleChip(index: Int)
    fun setUserCatalogName(name: String)
    fun addUserTarget(name: String, coords: String)
    fun editUserTarget(id: String, name: String, coords: String)
    fun removeUserTarget(id: String)
    fun startAddUserTarget()
    fun cancelAddUserTarget()
    fun toggleEditUserTarget(id: String)
    fun setQuery(text: String)
    fun clearQuery()
    fun selectTarget(id: String)
    fun togglePref(key: String)
    fun toggleCut(id: String)
    fun toggleDevice(key: String)
    fun selectDeviceName(key: String, name: String)
    fun setTrainRole(slot: TrainSlot, role: TrainRole, value: String)
    fun setTrainReducer(slot: TrainSlot, value: Double)

    fun snapMain()
    fun snapGuide()
    fun jogFocus(delta: Int)
    fun setRate(index: Int)
    fun setSlewDir(key: String)
    fun stopSlew()
    fun coolUp()
    fun coolDown()

    fun startProfile(name: String)
    fun stopProfile()
    fun selectProfile(name: String)
    fun toggleEkos()
    fun deleteProfile(name: String)
    fun editProfile(name: String)
    fun setRotatorAngle(deg: Double)
    fun setDomeOpen(open: Boolean)

    fun setIndiSwitch(deviceKey: String, propName: String, selected: Int)
    fun setIndiNumber(deviceKey: String, propName: String, value: Double)
    fun setIndiText(deviceKey: String, propName: String, value: String)

    fun openPa()
    fun paNext()
    fun setPaRate(index: Int)
    fun openBench()
    fun openSetup()
    fun setupBack()
    fun finishSetup()
    fun setScopeName(name: String)
    fun setOpticMm(mm: Int)
    fun setScopeApertureMm(mm: Int)
    fun setGuideScopeName(name: String)
    fun setGuideOpticMm(mm: Int)
    fun setGuideScopeApertureMm(mm: Int)
    fun setProfileName(name: String)
}
